feat:if文の追加
shionoya1019/issue_if pull request #1
Opened 2023-12-08 15:05 UTC by shionoya1019

2023-12-10 14:27 UTC, KatsuyaTanaka95 requested changes
素晴らしいです！！
（プルリクも素晴らしいです！教材をよく読んでいただきありがとうございます！）
（エンジニアに向いていますね！！！）
レビューさせていただきました！
より良くするために少し修正をお願いいたします！🙆🙋😊🌟💫

また、、改行は、`echo "<br>";`とするとできます！！！

2023-12-10 14:27 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +if ( $num >= 1 && $num <= 3 ) {
以下のように書くと、ぱっと見て理解がしやすいのでより良いです！！
`if (1 <= $num && $num <= 3 ) {`

修正してみましょう！！！！🙆😊

2023-12-11 12:15 UTC, shionoya1019 commented
ご確認・ご教示いただきありがとうございます！大変勉強になります…！

if文内の条件の並びと改行を修正しました。お手数ですがご確認をお願いいたします。

２つめのプルリク修正について質問なのですが、
同じファイルの修正なので「修正箇所が被る場合のレビュー待ち」になるかと思い
`feature/create-top-page`からプルリクを作成したのですが、このような使い方で合っておりますか？
（それとも同じファイルでも修正箇所自体が被っていなければmainからブランチをきってプルリク作成、でしょうか？）

2023-12-11 21:29 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-12-12 11:43 UTC, merged